version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_server
    command: uwsgi --ini uwsgi.ini --static-map /static=./static
    ports:
      - "8000:8000"