# Generated by Django 3.2 on 2022-01-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=128, null=True, verbose_name='书名')),
                ('desc', models.CharField(default=None, max_length=500, null=True, verbose_name='书描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '书表',
                'verbose_name_plural': '书',
                'db_table': 'book',
            },
        ),
    ]
