# Generated by Django 3.2 on 2022-01-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookTest', '0002_auto_20220104_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(default=None, help_text='书描述', max_length=500, null=True, verbose_name='书描述'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isSell',
            field=models.BooleanField(default=False, help_text='是否可卖', null=True, verbose_name='是否可卖'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default=None, help_text='书名', max_length=128, null=True, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='read',
            field=models.IntegerField(default=0, help_text='阅读量', null=True, verbose_name='阅读量'),
        ),
    ]
