# Generated by Django 3.2 on 2022-01-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='token'),
        ),
    ]
